export { default as Hero } from './hero'
export { default as homeSlider } from './homeSlider'
export { default as PopularCryptocurrencies } from './popularCryptocurrencies'
export { default as HomeFeed } from './homeFeed'
export { default as TokenRewards } from './tokenRewards'
export { default as EasySteps } from './easySteps'
export { default as ExploreEndless } from './exploreEndless'
export { default as CryptoExchange } from './cryptoExchange'
export { default as DownloadSelects } from './downloadSelects'
export { default as NeedHelp } from './needHelp'
export { default as StartEarning } from './startEarning'
export { default as footerSelects } from './footerSelects'
export { default as NavigationMenus } from './navigationMenus'
export { default as HeaderSearch } from './header/headerSearch'
export { default as QrDownload } from './header/qrDownload'
export { default as LanguageAndCurrency } from './header/languageAndCurrency'

